// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function Make(T) {
  return { };
}

var $$String = { };

var Country = { };

export {
  Make ,
  $$String ,
  Country ,
  
}
/* No side effect */
