// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Js_json from "bs-platform/lib/es6/js_json.js";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Async$Tripdeer from "./Async.bs.js";
import * as Promise$Tripdeer from "./Promise.bs.js";
import * as CountryT$Tripdeer from "../types/CountryT.bs.js";

var baseUrl = "https://tripdeer-9e870.firebaseio.com/.json?";

function passport(passport$1) {
  return "" + (String(baseUrl) + ("orderBy=\"Passport\"&equalTo=\"" + (String(passport$1) + "\"")));
}

var QueryBy = {
  passport: passport
};

function passport$1(passport$2, fn) {
  return Async$Tripdeer.let_(Promise$Tripdeer.$$fetch(passport(passport$2)), (function (res) {
                Curry._1(fn, Belt_List.fromArray(Belt_Option.mapWithDefault(Js_json.decodeObject(res), /* array */[], (function (json) {
                                return Belt_Array.keep(Belt_Array.map(Js_dict.values(json), (function (json) {
                                                  var match = CountryT$Tripdeer.result_decode(json);
                                                  if (match.tag) {
                                                    return {
                                                            destination: "",
                                                            passport: "",
                                                            code: 999
                                                          };
                                                  } else {
                                                    return match[0];
                                                  }
                                                })), (function (country) {
                                              return country.destination !== "";
                                            }));
                              }))));
                return Promise.resolve(/* () */0);
              }));
}

var Fetch = {
  passport: passport$1
};

export {
  baseUrl ,
  QueryBy ,
  Fetch ,
  
}
/* No side effect */
