// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";

function let_(prop, cb) {
  return prop.then(Curry.__1(cb));
}

export {
  let_ ,
  
}
/* No side effect */
