// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var apiKey = process.env.FIREBASE_API_KEY;

var authDomain = process.env.FIREBASE_AUTHDOMAIN;

var databaseUrl = process.env.FIREBASE_DATABASE_URL;

var projectId = process.env.FIREBASE_PROJECT_ID;

var storageBucket = process.env.FIREBASE_STORAGE_BUCKET;

var senderId = process.env.FIREBASE_MESSAING_SENDER_ID;

var firebaseAppId = process.env.FIREBASE_MESSAING_SENDER_ID;

var Firebase = {
  apiKey: apiKey,
  authDomain: authDomain,
  databaseUrl: databaseUrl,
  projectId: projectId,
  storageBucket: storageBucket,
  senderId: senderId,
  firebaseAppId: firebaseAppId,
  appId: firebaseAppId
};

export {
  Firebase ,
  
}
/* apiKey Not a pure module */
