// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as ReasonReact from "reason-react/src/ReasonReact.js";

var list = Belt_List.toArray;

var RR = {
  statelessComponent: ReasonReact.statelessComponent,
  statelessComponentWithRetainedProps: ReasonReact.statelessComponentWithRetainedProps,
  reducerComponent: ReasonReact.reducerComponent,
  reducerComponentWithRetainedProps: ReasonReact.reducerComponentWithRetainedProps,
  element: ReasonReact.element,
  wrapReasonForJs: ReasonReact.wrapReasonForJs,
  createDomElement: ReasonReact.createDomElement,
  wrapJsForReason: ReasonReact.wrapJsForReason,
  Router: ReasonReact.Router,
  list: list
};

function s(prim) {
  return prim;
}

export {
  RR ,
  s ,
  
}
/* ReasonReact Not a pure module */
