// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function $$fetch$1(url) {
  console.log(decodeURIComponent(url));
  return fetch(decodeURIComponent(url)).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(json);
              }));
}

export {
  $$fetch$1 as $$fetch,
  
}
/* No side effect */
