// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Printf from "bs-platform/lib/es6/printf.js";
import * as Belt_List from "bs-platform/lib/es6/belt_List.js";

var hours = Belt_List.makeBy(24, (function (i) {
        return i;
      }));

var miniutes = Belt_List.makeBy(60, (function (i) {
        return i;
      }));

function stringOfHour12(n) {
  if (n < 12) {
    return Curry._1(Printf.sprintf(/* Format */[
                    /* String */Block.__(2, [
                        /* No_padding */0,
                        /* String_literal */Block.__(11, [
                            " AM",
                            /* End_of_format */0
                          ])
                      ]),
                    "%s AM"
                  ]), String(n));
  } else {
    return Curry._1(Printf.sprintf(/* Format */[
                    /* String */Block.__(2, [
                        /* No_padding */0,
                        /* String_literal */Block.__(11, [
                            " PM",
                            /* End_of_format */0
                          ])
                      ]),
                    "%s PM"
                  ]), String(n - 12 | 0));
  }
}

function stringOfHour24(h) {
  return String(h);
}

function timeToString(t) {
  return String(t);
}

export {
  hours ,
  miniutes ,
  stringOfHour12 ,
  stringOfHour24 ,
  timeToString ,
  
}
/* hours Not a pure module */
