// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Emotion from "@ahrefs/bs-emotion/src/Emotion.bs.js";
import * as StyleVars$Tripdeer from "../StyleVars.bs.js";

var container = Emotion.css(undefined, /* :: */[
      Emotion.label("container"),
      /* :: */[
        Emotion.maxWidth(/* `px */[
              25096,
              590
            ]),
        /* :: */[
          Emotion.width(/* `pct */[
                5591841,
                100
              ]),
          /* [] */0
        ]
      ]
    ]);

var heading = Emotion.css(undefined, /* :: */[
      Emotion.label("heading"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              20
            ]),
        /* :: */[
          Emotion.fontWeight(300),
          /* :: */[
            Emotion.paddingBottom(/* `px */[
                  25096,
                  10
                ]),
            /* :: */[
              Emotion.textAlign(/* center */98248149),
              /* :: */[
                Emotion.color(StyleVars$Tripdeer.Color.primary),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var subHeading = Emotion.css(undefined, /* :: */[
      Emotion.label("subHeading"),
      /* :: */[
        Emotion.fontSize(/* `px */[
              25096,
              16
            ]),
        /* :: */[
          Emotion.fontWeight(300),
          /* :: */[
            Emotion.textAlign(/* center */98248149),
            /* :: */[
              Emotion.color(StyleVars$Tripdeer.Color.primary),
              /* :: */[
                Emotion.opacity(0.9),
                /* :: */[
                  Emotion.padding3(/* zero */-789508312, /* `px */[
                        25096,
                        40
                      ], /* `px */[
                        25096,
                        40
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var form = Emotion.css(undefined, /* :: */[
      Emotion.label("form"),
      /* :: */[
        Emotion.backgroundColor(/* `hex */[
              5194459,
              "f1f4ff"
            ]),
        /* :: */[
          Emotion.padding(/* `px */[
                25096,
                6
              ]),
          /* :: */[
            Emotion.borderRadius(/* `px */[
                  25096,
                  8
                ]),
            /* :: */[
              Emotion.boxShadow(/* zero */-789508312, /* `px */[
                    25096,
                    2
                  ], /* `px */[
                    25096,
                    3
                  ], /* zero */-789508312, false, /* `rgba */[
                    -878128972,
                    /* tuple */[
                      0,
                      0,
                      0,
                      0.1
                    ]
                  ]),
              /* :: */[
                Emotion.backgroundClip(/* paddingBox */972575930),
                /* :: */[
                  Emotion.select("[class$=\"control\"]", /* :: */[
                        Emotion.borderWidth(/* zero */-789508312),
                        /* :: */[
                          Emotion.boxShadow(undefined, undefined, undefined, undefined, undefined, /* transparent */582626130),
                          /* :: */[
                            Emotion.cursor(/* pointer */-786317123),
                            /* [] */0
                          ]
                        ]
                      ]),
                  /* :: */[
                    Emotion.select("[class*=\"select\"]", /* :: */[
                          Emotion.firstOfType(/* :: */[
                                Emotion.select("> div[class$=\"control\"]", /* :: */[
                                      Emotion.borderTopRightRadius(/* zero */-789508312),
                                      /* :: */[
                                        Emotion.borderBottomRightRadius(/* zero */-789508312),
                                        /* :: */[
                                          Emotion.after(/* :: */[
                                                Emotion.content("From"),
                                                /* :: */[
                                                  Emotion.position(/* absolute */-1013592457),
                                                  /* :: */[
                                                    Emotion.top(/* `px */[
                                                          25096,
                                                          13
                                                        ]),
                                                    /* :: */[
                                                      Emotion.fontSize(/* `px */[
                                                            25096,
                                                            9
                                                          ]),
                                                      /* :: */[
                                                        Emotion.fontWeight(700),
                                                        /* :: */[
                                                          Emotion.right(/* `px */[
                                                                25096,
                                                                56
                                                              ]),
                                                          /* :: */[
                                                            Emotion.opacity(0.6),
                                                            /* :: */[
                                                              Emotion.color(StyleVars$Tripdeer.Color.primary),
                                                              /* [] */0
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]
                                              ]),
                                          /* [] */0
                                        ]
                                      ]
                                    ]),
                                /* [] */0
                              ]),
                          /* :: */[
                            Emotion.lastOfType(/* :: */[
                                  Emotion.select("> div[class$=\"control\"]", /* :: */[
                                        Emotion.borderTopLeftRadius(/* zero */-789508312),
                                        /* :: */[
                                          Emotion.borderBottomLeftRadius(/* zero */-789508312),
                                          /* :: */[
                                            Emotion.after(/* :: */[
                                                  Emotion.content("To"),
                                                  /* :: */[
                                                    Emotion.position(/* absolute */-1013592457),
                                                    /* :: */[
                                                      Emotion.top(/* `px */[
                                                            25096,
                                                            13
                                                          ]),
                                                      /* :: */[
                                                        Emotion.fontSize(/* `px */[
                                                              25096,
                                                              9
                                                            ]),
                                                        /* :: */[
                                                          Emotion.fontWeight(700),
                                                          /* :: */[
                                                            Emotion.right(/* `px */[
                                                                  25096,
                                                                  56
                                                                ]),
                                                            /* :: */[
                                                              Emotion.opacity(0.6),
                                                              /* :: */[
                                                                Emotion.color(StyleVars$Tripdeer.Color.primary),
                                                                /* [] */0
                                                              ]
                                                            ]
                                                          ]
                                                        ]
                                                      ]
                                                    ]
                                                  ]
                                                ]),
                                            /* [] */0
                                          ]
                                        ]
                                      ]),
                                  /* [] */0
                                ]),
                            /* [] */0
                          ]
                        ]),
                    /* :: */[
                      Emotion.select("[class$=\"placeholder\"], [class$=\"singleValue\"], [class$=\"indicatorContainer\"]", /* :: */[
                            Emotion.color(StyleVars$Tripdeer.Color.primary),
                            /* [] */0
                          ]),
                      /* :: */[
                        Emotion.select("[class$=\"indicatorSeparator\"]", /* :: */[
                              Emotion.backgroundColor(StyleVars$Tripdeer.Color.primary),
                              /* [] */0
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var field = Emotion.css(undefined, /* :: */[
      Emotion.label("field"),
      /* :: */[
        Emotion.border(/* `px */[
              25096,
              2
            ], /* solid */12956715, StyleVars$Tripdeer.Color.primary),
        /* :: */[
          Emotion.borderRadius(/* `px */[
                25096,
                6
              ]),
          /* :: */[
            Emotion.minHeight(/* `px */[
                  25096,
                  30
                ]),
            /* :: */[
              Emotion.display(/* flex */-1010954439),
              /* :: */[
                Emotion.alignItems(/* center */98248149),
                /* :: */[
                  Emotion.padding(/* `px */[
                        25096,
                        4
                      ]),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var search = Emotion.css(undefined, /* :: */[
      Emotion.label("search"),
      /* :: */[
        Emotion.backgroundColor(StyleVars$Tripdeer.Color.primary),
        /* :: */[
          Emotion.padding(/* `px */[
                25096,
                11
              ]),
          /* :: */[
            Emotion.borderRadius(/* `px */[
                  25096,
                  4
                ]),
            /* :: */[
              Emotion.display(/* flex */-1010954439),
              /* :: */[
                Emotion.alignItems(/* center */98248149),
                /* :: */[
                  Emotion.marginRight(/* `px */[
                        25096,
                        4
                      ]),
                  /* :: */[
                    Emotion.marginLeft(/* `px */[
                          25096,
                          4
                        ]),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var select = Emotion.css(undefined, /* :: */[
      Emotion.label("select"),
      /* :: */[
        Emotion.flexGrow(1),
        /* [] */0
      ]
    ]);

export {
  container ,
  heading ,
  subHeading ,
  form ,
  field ,
  search ,
  select ,
  
}
/* container Not a pure module */
