// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Emotion from "@ahrefs/bs-emotion/src/Emotion.bs.js";
import * as StyleVars$Tripdeer from "../StyleVars.bs.js";

var container = Emotion.css(undefined, /* :: */[
      Emotion.label("container"),
      /* [] */0
    ]);

var title = Emotion.css(undefined, /* :: */[
      Emotion.label("title"),
      /* :: */[
        Emotion.marginBottom(/* `px */[
              25096,
              40
            ]),
        /* :: */[
          Emotion.fontWeight(900),
          /* :: */[
            Emotion.fontSize(/* `px */[
                  25096,
                  28
                ]),
            /* [] */0
          ]
        ]
      ]
    ]);

var list = Emotion.css(undefined, /* :: */[
      Emotion.label("list"),
      /* :: */[
        Emotion.listStyleType(/* none */-922086728),
        /* [] */0
      ]
    ]);

var listItem = Emotion.css(undefined, /* :: */[
      Emotion.label("listItem"),
      /* :: */[
        Emotion.margin(/* zero */-789508312),
        /* :: */[
          Emotion.padding4(/* zero */-789508312, /* zero */-789508312, /* `px */[
                25096,
                40
              ], /* `px */[
                25096,
                20
              ]),
          /* :: */[
            Emotion.position(/* relative */903134412),
            /* :: */[
              Emotion.after(/* :: */[
                    Emotion.content(""),
                    /* :: */[
                      Emotion.borderLeft(/* `px */[
                            25096,
                            3
                          ], /* solid */12956715, /* `hex */[
                            5194459,
                            "e4e4e4"
                          ]),
                      /* :: */[
                        Emotion.position(/* absolute */-1013592457),
                        /* :: */[
                          Emotion.left(/* `px */[
                                25096,
                                -15
                              ]),
                          /* :: */[
                            Emotion.height(/* `pct */[
                                  5591841,
                                  100
                                ]),
                            /* :: */[
                              Emotion.top(/* zero */-789508312),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]),
              /* :: */[
                Emotion.before(/* :: */[
                      Emotion.content(""),
                      /* :: */[
                        Emotion.position(/* absolute */-1013592457),
                        /* :: */[
                          Emotion.left(/* `px */[
                                25096,
                                -20
                              ]),
                          /* :: */[
                            Emotion.display(/* block */888960333),
                            /* :: */[
                              Emotion.width(/* `px */[
                                    25096,
                                    14
                                  ]),
                              /* :: */[
                                Emotion.height(/* `px */[
                                      25096,
                                      14
                                    ]),
                                /* :: */[
                                  Emotion.top(/* zero */-789508312),
                                  /* :: */[
                                    Emotion.backgroundColor(StyleVars$Tripdeer.Color.primary),
                                    /* :: */[
                                      Emotion.borderRadius(/* `pct */[
                                            5591841,
                                            50
                                          ]),
                                      /* :: */[
                                        Emotion.zIndex(1),
                                        /* [] */0
                                      ]
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]
                      ]
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  container ,
  title ,
  list ,
  listItem ,
  
}
/* container Not a pure module */
