// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Component1$Tripdeer = require("./Component1.bs.js");
var Component2$Tripdeer = require("./Component2.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Component1$Tripdeer.make, {
          message: "Hello! Click this nihao."
        }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(Component2$Tripdeer.make, {
          greeting: "Hello!"
        }), "index2");

/*  Not a pure module */
