// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Emotion from "@ahrefs/bs-emotion/src/Emotion.bs.js";
import * as StyleVars$Tripdeer from "../StyleVars.bs.js";

var button = Emotion.css(undefined, /* :: */[
      Emotion.label("button"),
      /* :: */[
        Emotion.backgroundColor(StyleVars$Tripdeer.Color.primary),
        /* :: */[
          Emotion.borderRadius(/* `px */[
                25096,
                3
              ]),
          /* :: */[
            Emotion.display(/* inlineBlock */-147785676),
            /* :: */[
              Emotion.borderWidth(/* zero */-789508312),
              /* :: */[
                Emotion.outlineWidth(/* zero */-789508312),
                /* :: */[
                  Emotion.color(Emotion.Css.Color.white),
                  /* :: */[
                    Emotion.padding2(/* `px */[
                          25096,
                          10
                        ], /* `px */[
                          25096,
                          20
                        ]),
                    /* :: */[
                      Emotion.fontSize(/* `px */[
                            25096,
                            14
                          ]),
                      /* :: */[
                        Emotion.fontWeight(300),
                        /* :: */[
                          Emotion.cursor(/* pointer */-786317123),
                          /* :: */[
                            Emotion.hover(/* :: */[
                                  Emotion.backgroundColor(StyleVars$Tripdeer.Color.primaryHover),
                                  /* [] */0
                                ]),
                            /* :: */[
                              Emotion.active(/* :: */[
                                    Emotion.backgroundColor(StyleVars$Tripdeer.Color.primaryActive),
                                    /* [] */0
                                  ]),
                              /* [] */0
                            ]
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  button ,
  
}
/* button Not a pure module */
