// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Cn from "re-classnames/src/Cn.bs.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Button_Css$Tripdeer from "./Button_Css.bs.js";

function Button(Props) {
  var className = Props.className;
  var onClick = Props.onClick;
  var children = Props.children;
  var tmp = {
    className: Cn.make(/* :: */[
          Button_Css$Tripdeer.button,
          /* :: */[
            Cn.unpack(className),
            /* [] */0
          ]
        ])
  };
  if (onClick !== undefined) {
    tmp.onClick = Caml_option.valFromOption(onClick);
  }
  return React.createElement("button", tmp, children);
}

var Css = /* alias */0;

var make = Button;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
