// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Emotion from "@ahrefs/bs-emotion/src/Emotion.bs.js";

var day = Emotion.css(undefined, /* :: */[
      Emotion.label("day"),
      /* :: */[
        Emotion.position(/* absolute */-1013592457),
        /* :: */[
          Emotion.outlineWidth(/* zero */-789508312),
          /* :: */[
            Emotion.fontSize(/* `px */[
                  25096,
                  18
                ]),
            /* :: */[
              Emotion.left(/* `px */[
                    25096,
                    -200
                  ]),
              /* :: */[
                Emotion.width(/* `px */[
                      25096,
                      150
                    ]),
                /* :: */[
                  Emotion.textAlign(/* right */-379319332),
                  /* :: */[
                    Emotion.fontWeight(900),
                    /* :: */[
                      Emotion.color(/* `rgba */[
                            -878128972,
                            /* tuple */[
                              0,
                              0,
                              0,
                              0.3
                            ]
                          ]),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var placeHolder = Emotion.css(undefined, /* :: */[
      Emotion.label("placeHolder"),
      /* :: */[
        Emotion.position(/* absolute */-1013592457),
        /* :: */[
          Emotion.color(/* `rgba */[
                -878128972,
                /* tuple */[
                  0,
                  0,
                  0,
                  0.3
                ]
              ]),
          /* :: */[
            Emotion.zIndex(0),
            /* :: */[
              Emotion.display(/* none */-922086728),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var editable = Emotion.css(undefined, /* :: */[
      Emotion.label("editable"),
      /* :: */[
        Emotion.position(/* relative */903134412),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                18
              ]),
          /* :: */[
            Emotion.fontWeight(300),
            /* :: */[
              Emotion.hover(/* :: */[
                    Emotion.select("." + (String(placeHolder) + ""), /* :: */[
                          Emotion.display(/* block */888960333),
                          /* [] */0
                        ]),
                    /* [] */0
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var editableContent = Emotion.css(undefined, /* :: */[
      Emotion.label("editableContent"),
      /* :: */[
        Emotion.outlineWidth(/* zero */-789508312),
        /* :: */[
          Emotion.position(/* relative */903134412),
          /* :: */[
            Emotion.zIndex(1),
            /* [] */0
          ]
        ]
      ]
    ]);

export {
  day ,
  placeHolder ,
  editable ,
  editableContent ,
  
}
/* day Not a pure module */
