// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Printf from "bs-platform/lib/es6/printf.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Button$Tripdeer from "./Button.bs.js";
import * as Airline$Tripdeer from "./icons/Airline.bs.js";
import * as Prelude$Tripdeer from "../helpers/Prelude.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as VisaResult_Css$Tripdeer from "./VisaResult_Css.bs.js";

function VisaResult(Props) {
  var children = Props.children;
  var to_ = Props.to_;
  var match = Props.noResult;
  var noResult = match !== undefined ? match : false;
  var match$1 = !noResult;
  return React.createElement("div", {
              className: VisaResult_Css$Tripdeer.result
            }, children, match$1 ? React.createElement(React.Fragment, undefined, React.createElement("div", {
                        className: VisaResult_Css$Tripdeer.airline
                      }, React.createElement(Airline$Tripdeer.make, { })), React.createElement(Button$Tripdeer.make, {
                        className: VisaResult_Css$Tripdeer.button,
                        onClick: (function (param) {
                            return ReasonReactRouter.push("/itinerary" + Belt_Option.mapWithDefault(to_, "", (function (to_) {
                                              return Curry._1(Printf.sprintf(/* Format */[
                                                              /* String_literal */Block.__(11, [
                                                                  "?country=",
                                                                  /* String */Block.__(2, [
                                                                      /* No_padding */0,
                                                                      /* End_of_format */0
                                                                    ])
                                                                ]),
                                                              "?country=%s"
                                                            ]), to_.label);
                                            })));
                          }),
                        children: Prelude$Tripdeer.s("Create your itinerary")
                      })) : null);
}

var Css = /* alias */0;

var make = VisaResult;

export {
  Css ,
  make ,
  
}
/* react Not a pure module */
