// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Emotion from "@ahrefs/bs-emotion/src/Emotion.bs.js";
import * as StyleVars$Tripdeer from "../StyleVars.bs.js";

var result = Emotion.css(undefined, /* :: */[
      Emotion.label("result"),
      /* :: */[
        Emotion.marginTop(/* `px */[
              25096,
              10
            ]),
        /* :: */[
          Emotion.backgroundColor(Emotion.Css.Color.white),
          /* :: */[
            Emotion.padding(/* `px */[
                  25096,
                  20
                ]),
            /* :: */[
              Emotion.borderRadius(/* `px */[
                    25096,
                    8
                  ]),
              /* :: */[
                Emotion.boxShadow(/* zero */-789508312, /* `px */[
                      25096,
                      2
                    ], /* `px */[
                      25096,
                      3
                    ], /* zero */-789508312, false, /* `rgba */[
                      -878128972,
                      /* tuple */[
                        0,
                        0,
                        0,
                        0.1
                      ]
                    ]),
                /* :: */[
                  Emotion.backgroundClip(/* paddingBox */972575930),
                  /* :: */[
                    Emotion.position(/* relative */903134412),
                    /* :: */[
                      Emotion.fontSize(/* `px */[
                            25096,
                            16
                          ]),
                      /* :: */[
                        Emotion.color(StyleVars$Tripdeer.Color.primary),
                        /* :: */[
                          Emotion.textAlign(/* center */98248149),
                          /* :: */[
                            Emotion.fontWeight(900),
                            /* [] */0
                          ]
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var airline = Emotion.css(undefined, /* :: */[
      Emotion.label("airline"),
      /* :: */[
        Emotion.display(/* block */888960333),
        /* :: */[
          Emotion.position(/* absolute */-1013592457),
          /* :: */[
            Emotion.top(/* `px */[
                  25096,
                  50
                ]),
            /* :: */[
              Emotion.left(/* `px */[
                    25096,
                    8
                  ]),
              /* :: */[
                Emotion.width(/* `calc */[
                      -1044768619,
                      /* tuple */[
                        /* sub */5745024,
                        /* `pct */[
                          5591841,
                          100
                        ],
                        /* `px */[
                          25096,
                          16
                        ]
                      ]
                    ]),
                /* :: */[
                  Emotion.textAlign(/* right */-379319332),
                  /* :: */[
                    Emotion.after(/* :: */[
                          Emotion.content(""),
                          /* :: */[
                            Emotion.position(/* absolute */-1013592457),
                            /* :: */[
                              Emotion.left(/* zero */-789508312),
                              /* :: */[
                                Emotion.top(/* `px */[
                                      25096,
                                      8
                                    ]),
                                /* :: */[
                                  Emotion.width(/* `pct */[
                                        5591841,
                                        100
                                      ]),
                                  /* :: */[
                                    Emotion.borderBottom(/* `px */[
                                          25096,
                                          1
                                        ], /* dashed */568403505, Emotion.Css.Color.black),
                                    /* :: */[
                                      Emotion.opacity(0.1),
                                      /* [] */0
                                    ]
                                  ]
                                ]
                              ]
                            ]
                          ]
                        ]),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var button = Emotion.css(undefined, /* :: */[
      Emotion.label("button"),
      /* :: */[
        Emotion.marginTop(/* `px */[
              25096,
              40
            ]),
        /* :: */[
          Emotion.display(/* block */888960333),
          /* :: */[
            Emotion.marginLeft(/* auto */-1065951377),
            /* :: */[
              Emotion.marginRight(/* auto */-1065951377),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

export {
  result ,
  airline ,
  button ,
  
}
/* result Not a pure module */
