// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Airline(Props) {
  return React.createElement("svg", {
              height: "16px",
              width: "16px",
              version: "1.1",
              viewBox: "0 0 1000 1000"
            }, React.createElement("g", undefined, React.createElement("path", {
                      d: "M647,436.3"
                    }), React.createElement("path", {
                      d: "M990,500c0-39.2-34.3-73.5-73.5-73.5H647l-245-392h-98l122.5,392H157l-73.5-98H10L59,500L10,671.5h73.5l73.5-98h269.5L304,965.5h98l245-392h269.5C955.7,573.5,990,539.2,990,500z",
                      fill: "#5841d0"
                    })));
}

var make = Airline;

export {
  make ,
  
}
/* react Not a pure module */
