// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Home$Tripdeer from "./pages/Home.bs.js";
import * as App_Css$Tripdeer from "./App_Css.bs.js";
import * as Prelude$Tripdeer from "./helpers/Prelude.bs.js";
import * as RouterT$Tripdeer from "./types/RouterT.bs.js";
import * as ReasonReactRouter from "reason-react/src/ReasonReactRouter.js";
import * as Itinerary$Tripdeer from "./pages/Itinerary.bs.js";

function reducer(param, action) {
  return {
          route: action[0]
        };
}

function App(Props) {
  var match = React.useReducer(reducer, {
        route: /* Home */0
      });
  var dispatch = match[1];
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  React.useEffect((function () {
          Curry._1(dispatch, /* RouterChanged */[RouterT$Tripdeer.cleanPath(url.path)]);
          return ;
        }), /* array */[url]);
  var tmp;
  switch (match[0].route) {
    case /* Home */0 :
        tmp = React.createElement(Home$Tripdeer.make, { });
        break;
    case /* Itinerary */1 :
        tmp = React.createElement(Itinerary$Tripdeer.make, {
              search: url.search
            });
        break;
    case /* NotFound */2 :
        tmp = Prelude$Tripdeer.s("Not found");
        break;
    
  }
  return React.createElement("div", {
              className: App_Css$Tripdeer.container
            }, tmp);
}

var Css = /* alias */0;

var make = App;

export {
  Css ,
  reducer ,
  make ,
  
}
/* react Not a pure module */
