// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Emotion from "@ahrefs/bs-emotion/src/Emotion.bs.js";

var container = Emotion.css(undefined, /* :: */[
      Emotion.label("container"),
      /* :: */[
        Emotion.maxWidth(/* `px */[
              25096,
              768
            ]),
        /* :: */[
          Emotion.width(/* `pct */[
                5591841,
                100
              ]),
          /* [] */0
        ]
      ]
    ]);

export {
  container ,
  
}
/* container Not a pure module */
