// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Emotion from "@ahrefs/bs-emotion/src/Emotion.bs.js";

Emotion.$$global("html, body", /* :: */[
      Emotion.margin(/* zero */-789508312),
      /* :: */[
        Emotion.padding(/* zero */-789508312),
        /* :: */[
          Emotion.minHeight(Emotion.pct(100)),
          /* :: */[
            Emotion.height(Emotion.pct(100)),
            /* :: */[
              Emotion.fontFamily("Helvetica Neue,Helvetica,Arial,sans-serif"),
              /* :: */[
                Emotion.color(/* `hex */[
                      5194459,
                      "333"
                    ]),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

Emotion.$$global("#root", /* :: */[
      Emotion.display(/* flex */-1010954439),
      /* :: */[
        Emotion.justifyContent(/* center */98248149),
        /* :: */[
          Emotion.alignItems(/* center */98248149),
          /* :: */[
            Emotion.height(Emotion.pct(100)),
            /* :: */[
              Emotion.backgroundColor(/* `hex */[
                    5194459,
                    "f5f5f5"
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

Emotion.$$global("h1, h2, h3, h4, h5, h6", /* :: */[
      Emotion.fontFamily("Roboto, sans-serif"),
      /* :: */[
        Emotion.fontWeight(500),
        /* :: */[
          Emotion.margin(/* zero */-789508312),
          /* :: */[
            Emotion.padding(/* zero */-789508312),
            /* [] */0
          ]
        ]
      ]
    ]);

export {
  
}
/*  Not a pure module */
