// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as App$Tripdeer from "./App.bs.js";
import * as Global_Css$Tripdeer from "./Global_Css.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App$Tripdeer.make, { }), "root");

export {
  
}
/*  Not a pure module */
