// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


var Color_primary = /* `hex */[
  5194459,
  "5841d0"
];

var Color_primaryHover = /* `hex */[
  5194459,
  "4d39b7"
];

var Color_primaryActive = /* `hex */[
  5194459,
  "3e2e90"
];

var Color = {
  primary: Color_primary,
  primaryHover: Color_primaryHover,
  primaryActive: Color_primaryActive
};

export {
  Color ,
  
}
/* No side effect */
